services:

  ###############################
  ##         [Node]            ##
  ###############################
  node:
    build:
      context: .
      args:
        NODE_VERSION_SET_IMAGE: node:${NODE_VERSION_SET}-alpine
    container_name: ${NAMESPACE}_node
    restart: always
    ports:
      - 3000:3000
