<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPrOxePE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPrOxePE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPrOxePE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPrOxePE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPrOxePE\App_KernelDevDebugContainer([
    'container.build_hash' => 'PrOxePE',
    'container.build_id' => 'ff8a2671',
    'container.build_time' => 1716412238,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPrOxePE');
