name: CI frontend

on:
  pull_request:
    branches:
      - 'main'
jobs:
  coding-standard:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22 ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: pnpm install
        working-directory: "frontend"
      - name: Run linter
        run: pnpm run lint
        working-directory: "frontend"
      - name: Build project
        run:  pnpm run build
        working-directory: "frontend"